---
title: "Feature Selection for CATS"
output:
  html_document:
    df_print: paged
    team: 8
    authors: Nick Bounatsos
---

```{r}
setwd('C:/Users/nikos/OneDrive/Έγγραφα/MSc/Classes/Bioinformatics for Translational Medicine/bstm-project')
```

```{r}
library('caret')
library('gbm')
```

```{r}
data<-read.delim('train_call.tsv', header = TRUE, sep = "\t", quote = "\"", dec = ".",
fill = TRUE, comment.char = "")
```

```{r}
data<-t(data)
```

```{r}
clinic<-read.delim('train_clinical.txt', header = TRUE, sep = "\t", quote = "\"", dec = ".", fill = TRUE, comment.char = "",row.names='Sample')
```

```{r}
Combo<-merge(clinic, data, by="row.names")
row.names(Combo)<-Combo$Row.names
Combo$Row.names<-NULL
```

```{r}
rocVarImp<-filterVarImp(Combo[,-1], as.factor(Combo[,1]), nonpara = FALSE)
```

```{r}
head(rocVarImp)
```

```{r}
final<-apply(rocVarImp, 1, mean)
```

```{r}
features<-final[order(final,decreasing = TRUE)]
```

```{r}
features<-as.data.frame(features)
```

```{r}
barplot(features$features[1:20],names.arg=row.names(features)[1:20], cex.axis = 1, cex.names = 0.4, xlab = "Feature name", ylab = "Feature importance", main = "Top 20 important features")
```

```{r}
write.csv(Combo, "combo.csv", row.names=TRUE)
write.csv(features,"features.csv", row.names=FALSE)
```
